name: Build Safari Extension
on:
  push:
    branches:
      - main # åªæœ‰æ¨é€åˆ° main åˆ†æ”¯æ—¶æ‰ä¼šè§¦å‘æ„å»º

jobs:
  build:
    name: Build extensions with bepp
    runs-on: macos-latest # Must be macos for Safari extension build
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build extension with BEPP
        uses: pigeonposse/bepp@v1
      - name: View builds
        runs: ls -ls build/extensions # this is the default output for builds, you can change output folder in bepp config file.
